version: '2'
services:
  db:
    image: "postgres:alpine"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=weather
      - POSTGRES_PASSWORD=forecast
      - POSTGRES_DB=weather_accuracy
  web:
    build: .
    links:
      - db
